name: Snyk

on:
  push:
    branches: [ master ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        with:
          command: monitor
          args: --prune-repeated-subdependencies --project-name=snowplow-golang-analytics-sdk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}